### PR TITLE
Add vspd.stakey.com to VSP list and remove Stakepool stakey.com

### PR DESCRIPTION
**Pull request by dema501**

### CODE REVIEW

**Comment by dajohi** [comment]
Please add tls 1.3 and remove tls 1.1

**Comment by dema501** [comment]
> Please add tls 1.3 and remove tls 1.1
@dajohi  it's done

**Comment by xaur** [comment]
I think `"vspdversion":"1.0.0-pre"` shouldn't have "pre" in it now that v1.0.0 final is out, per the [deployment](https://github.com/decred/vspd/blob/master/docs/deployment.md#build-from-source) guide.

**Comment by dema501** [comment]
> I think `"vspdversion":"1.0.0-pre"` shouldn't have "pre" in it now that v1.0.0 final is out, per the [deployment](https://github.com/decred/vspd/blob/master/docs/deployment.md#build-from-source) guide.

ok, built from release-v1.0 branch rather than master

**Comment by xaur** [comment]
I guess we're still waiting for the first voted ticket. vspinfo endpoint reports 0 currently.

I wonder why remove https://stakey.com too, and most importantly, will it keep running until all live tickets vote?

**Review by jholdstock — APPROVED** [review]

**Comment by xaur** [comment]
@dema501 please upgrade your legacy dcrstakepool's dcrd/dcrwallet ASAP.

https://stakey.com/api/v2/stats reports block 552447 and it means it is forked off while it still had 79 live tickets. Every Decred block of downtime there is a risk your VSP will miss client's tickets, damaging reputation of stakey.com and Decred in general.

**Pull request merged**
