### PR TITLE
add mainnet VSP vote.dcr-swiss.ch

### PR DESCRIPTION
**Pull request by dcr-swiss**

### CODE REVIEW

**Review by jholdstock — APPROVED** [review]

**Comment by xaur** [comment]
I see [7 live tickets](https://vote.dcr-swiss.ch/). Is this good to go?

**Comment by dcr-swiss** [comment]
we are ready 👍

**Comment by jholdstock** [comment]
@dajohi could you merge and deploy please?

**Review by dajohi — APPROVED** [review]

**Comment by dcr-swiss** [comment]
I replied on matrix. Thanks for merging

**Pull request merged**
