### PR TITLE
Remove legacy stakepools

### PR DESCRIPTION
**Pull request by jholdstock**
Marking this as a draft until:
1. ~VSPs have updated to vspd 1.1.0~
1. ~Corresponding dcrweb PR is ready~
1. Decrediton is ready

### CODE REVIEW

**Comment by xaur** [comment]
tbh I would remove Legacy VSP from the API sooner without blocking on the other stuff.

Now that the chain has forked, all but two items in the https://api.decred.org/?c=gsd response are stuck on an old block height or have zeroes in all fields. I'm puzzled how decredbrasil.com and coinmine.pl manage to follow the chain (and decredbrasil.com even has `"PoolStatus":"Open"` in its individual API) but unless they still work _for real_, I think it's fair to remove all legacy VSP stuff from the API and from https://decred.org/vsp/

**Comment by jholdstock** [comment]
Need confirmation from decrediton before removing the legacy stakepool API, we don't want it displaying errors when the endpoint disappears @alexlyp

**Comment by alexlyp** [comment]
@bgptr will remove any reference in decrediton to the legacy stakepool.  That will be merged soon after it's all done.  Not sure when we'll want this to go in, but probably will need to wait until the next release that includes it.

**Comment by xaur** [comment]
How about returning an empty list of legacy VSPs for now, to proceed with this PR?

**Comment by jholdstock** [comment]
This should be good to merge now that Decrediton 1.8 is released. I have confirmed no other code is calling this old endpoint.

**Review by dajohi — APPROVED** [review]

**Pull request merged**
