### PR TITLE
Add dcrpool.ibitlin.com

### PR DESCRIPTION
**Pull request by lealife**

### CODE REVIEW

**Comment by jholdstock** [comment]
Hi there @lealife, we need to see voted tickets on your VSP before it will be added to the API. Also, the website at https://dcrpool.ibitlin.com/vspd/ appears to be incredibly unresponsive to me - is there any reason for that?

**Comment by dajohi** [comment]
@lealife please rebase.

**Comment by lealife** [comment]
image
Waiting for voting...

**Comment by lealife** [comment]
image

**Comment by lealife** [comment]
@dajohi @jholdstock 
See https://dcrpool.ibitlin.com/vspd/
please merge the pull request https://github.com/decred/dcrwebapi/pull/122, thanks

**Review by jholdstock — APPROVED** [review]

**Pull request merged**
