### PR TITLE
add 2 new stake pools

### PR DESCRIPTION
**Pull request by jolan**
@dajohi Should #4 go in first or how did you want to handle that & this?

### CODE REVIEW

**Comment by dnldd** [comment]
@jolan I can update #4 with the new stakepools so it's on par with the php version and ready when the switch is made, should I go ahead?

**Comment by jolan** [comment]
@dnldd Please do and I'll go ahead and close this, thanks.

**Comment by dnldd** [comment]
added, don't think you should close this though. I think there are more tests lined up #4 before the switch so this should get merged whiles that is sorted out.

**Comment by dajohi** [comment]
@jolan @dnldd rebase or close?

**Comment by jolan** [comment]
This got included in #4.  Closing.

**Pull request closed without merging**
